language: node_js
node_js:
  - 12.12.0
install:
  - npm install
script:
  - npm test
deploy:
  provider: pages
  skip_cleanup: true
  github_token: GITHUB_TOKEN
  keep_history: true
  on:
    branch: master
